### ISSUE TITLE
pcCenter report -D not working

### ISSUE THREAD

**Issue by gerardo-herzig** [lesovsky/pgcenter#97] opened 2021-05-31 17:35 UTC
Showing Database Report is not working after https://github.com/lesovsky/pgcenter/issues/96

Showing `backends` now works for pg 12 (not tested on 13), but  isnt working for 9.6, 10 nor 11:

Using the latest patch:
```
gerardo@SnarF ~/pgcenter/pgcenter (master) $ /usr/bin/pgcenter --version
pgcenter v0.8.0 f5d048a-master
gerardo@SnarF ~/pgcenter/pgcenter (master) $ git pull
Already up to date.
```

```
gerardo@SnarF ~ $ psql -p5432 -c "show server_version"
 server_version 
----------------
10.15 (Ubuntu 10.15-0ubuntu0.18.04.1)
```

```
gerardo@SnarF ~/pgcenter/pgcenter (master) $ > pgcenter.stat.tar; /usr/bin/pgcenter -Upostgres record -p5432 -c 10
INFO: some statistics is not supported by the current version of Postgres and will be skipped
INFO: recording to pgcenter.stat.tar

## CLEAN UP REPORT FILE AND START REPORTING
gerardo@SnarF ~/pgcenter/pgcenter (master) $ /usr/bin/pgcenter report -D
INFO: reading from pgcenter.stat.tar
INFO: report databases
INFO: start from: 0001-01-01 00:00:00 LMT, to: 2021-05-31 14:31:42 -03, with rate: 1s
diff failed: convert '' to int failed: strconv.ParseInt: parsing "": invalid syntax
```

**Comment by lesovsky** [comment] 2021-05-31 17:46
Confirmed, it is broken on 9.5, 9.6, 10, 11, 12 and working on 13, 14.
Thanks for report.

**Comment by lesovsky** [comment] 2021-06-06 13:22
The problem is related to pgcenter doesn't take into account version of Postgres from which stats was recorded. 
I've added logic which does that. Could you build pgcenter using master branch and  try to reproduce the problem. Files written by old pgcenter should be discarded.

**Comment by lesovsky** [comment] 2021-06-15 16:48
The issue is related to due to `record` creates two or more files with the same name in tar archive. When `report` reads these files it crashes because failed to calculate interval properly. New v0.9.0 uses milliseconds in filenames, which avoid situations with duplicate names, and issue should be fixed.

**Closed by lesovsky** 2021-06-15 16:48 UTC
