### ISSUE TITLE
var PGPORT dont used

### ISSUE THREAD

**Issue by shab2** [lesovsky/pgcenter#85] opened 2020-12-25 11:22 UTC
Hi, Alexey

<runing successful>

[PCFT]$ pgcenter top --port=5434 pcft
SSL is not enabled on the server, connecting with sslmode=disable

<runing not successful>

[PCFT]$ echo $PGPORT
5434
[PCFT]$ pgcenter top pcft
ERROR: failed connection establishing: dial tcp 127.0.0.1:5432: connect: connection refused

**Comment by lesovsky** [comment] 2020-12-25 11:39
Confirmed, thanks. Will fix it in 'refactoring' branch.

**Comment by lesovsky** [comment] 2021-02-13 10:32
@shab2 fixed in v0.7.0.
The cause was port option was overwritten by cmd defaults.

**Closed** 2021-06-15 16:41 UTC
