### ISSUE TITLE
./pgcenter: cannot execute binary file

### ISSUE THREAD

**Issue by Splarv** [lesovsky/pgcenter#56] opened 2019-02-11 12:09 UTC
git clone https://github.com/lesovsky/pgcenter.git --single-branch --depth=1

$ make
go mod download
CGO_ENABLED=0 GOOS=linux GOARCH= go build -ldflags "-X main.COMMIT=9b148b446e53d558191fa63e86843bb0ae79cd86 -X main.BRANCH=master" -o pgcenter pgcenter.go

$  ./pgcenter
-bash: ./pgcenter: cannot execute binary file

$ ls -la pgcenter
-rwxr-xr-x  1 olleg  staff  9053984 11 фев 15:06 pgcenter

MacOs 10.14.2, 
$ go version
go version go1.11.5 darwin/amd64

**Comment by lesovsky** [comment] 2019-02-11 12:27
Maybe you're trying to exec binary from filesystem which is mounted with `noexec` flag?
Examine the output of `mount` command.

**Comment by Splarv** [comment] 2019-02-11 12:39
Heh, workaround is to change in Makefile GOOS=linux to GOOS=darwin. And pgcenter works in MacOS.

**Comment by lesovsky** [comment] 2019-02-11 12:40
Wow )))

**Comment by lesovsky** [comment] 2019-02-11 15:18
If there is no other problems with build process, I close the issue.

**Closed by lesovsky** 2019-02-11 15:18 UTC

**Comment by Splarv** [comment] 2019-02-11 15:55
Okey, as I can see you don't support other OS then linux, so it can be a bug.

**Comment by lesovsky** [comment] 2019-02-11 16:02
Yes, I don't support other OSes than Linux, because of
1. pgcenter relies on `procfs` filesystem which is very Linux-specific.
2. I have no MacOS, so I can't properly test all pgcenter's functionality.

In the end, I think it's not a bug, because you're trying to compile program on unsupported OS, where proper work is not guaranteed.
Alas ))
